#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# Setup the module files correctly
#

source $MODULESHOME/init/zsh
# Setup anantha-group programs
export progs=/u/anantha/workspace3/share/programs
module add rh6-libs
module add python
module add bluespec

# Setup user programs
module use $HOME/programs/modulefiles/
module add local

# Setup MTL programs
local m
local ms=()
for m in /u/cad/modulefiles/*
do
  if [[ -d $m && -r $m ]]
  then
    ms+="$m"
  fi
done
module use $ms
