#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
bindkey '^ ' autosuggest-accept
bindkey 'jk' vi-cmd-mode

# bind UP and DOWN arrow keys
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# bind P and N for EMACS mode
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down

# bind k and j for VI mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

export MANPAGER="less"
export EDITOR="vim"
export HOSTALIASES="/homes/chiraag/.host_aliases"

alias gitdiffcolor="git diff --color=always | less -R"

# added by Anaconda3 installer
export PATH="/home/chiraag/anaconda3/bin:$PATH"
export DISPLAY=localhost:0.0

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

setopt HIST_IGNORE_SPACE

. /home/chiraag/anaconda3/etc/profile.d/conda.sh

